# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: gateway                  # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Sendet Kommandos an lircd das wiederum IR-Signale an Geräte mit IR-Schnittstelle versendet'
        en: 'Sends commands to lircd that sends IR-signals to any device that has an IR-interface'
    maintainer: E3EAT
    tester: Onkelandy
    keywords: infrared
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/lirc/....md
#    support:

    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: True           # plugin supports multi instance
    classname: LIRC                # class containing the plugin


parameters:
    # Definition of parameters to be configured in etc/plugin.yaml

    instance:
        type: str
        mandatory: True
        description:
            de: 'Name der Plugin Instanz (SmartHomeNG Standard-Parameter). Die Angabe ist notwendig um den passenden lircd zu ermitteln wenn ein Befehl versendet werden soll.'
            en: 'Name of the plugin instance (SmartHomeNG standard parameter). This is mandatory to identify the matching lircd for a pending command.'

    lirc_host:
        type: str
        mandatory: True
        description:
            de: 'IP oder Hostname des lircd'
            en: 'IP or hostname of the lircd'

    lirc_port:
        type: int
        default: 8765
        description:
            de: 'Der Port auf dem lircd lauscht.'
            en: 'The port that is used by lircd.'
