# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    subtype: core                 # plugin subtype (if applicable)
    description:                  # Alternative: description in multiple languages
        de: 'Command Line Interface für SmartHomeNG - Letzte Version, die das Logics-API nicht benötigt, funktioniert bis SmartHomeNG v1.3'
        en: 'Commandline interface for SmartHomeNG - Last version not depending on the logics-API, works up to SmartHomeNG v1.3'
    maintainer: cmalo (mknx)
    tester: onkelandy, Sandman60, ohinckel
#    keywords: iot xyz
    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page

    version: 1.3.0                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    sh_maxversion: 1.3c            # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance
    classname: CLI                 # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
