# Metadata for the Smart-Plugin
plugin:
    # Global plugin attributes
    type: system                  # plugin type (gateway, interface, protocol, system, web)
    subtype: core                 # plugin subtype (if applicable)
    description:                  # Alternative: description in multiple languages
        de: 'Web Interface zur Anzeige von Informationen zum System und SmartHomeNG Backend-Daten'
        en: 'webinterface for displaying system information and SmartHomeNG backend data'
    maintainer: psilo909, msinn, bmxp
    tester: Sandman60
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page

    version: 1.3.5                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    sh_maxversion: 1.3a            # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False          # plugin supports multi instance

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
item_attributes:
    # Definition of item attributes defined by this plugin
    
