plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: '1-Wire Unterstützung über owserver'
        en: '1-Wire support via owserver'
        fr: 'Support de 1-Wire à travers owserver'
    maintainer: cmalo (mknx)
    keywords: 1wire onewire
    version: 1.3.1                 # Plugin version
    sh_minversion: 1.3             # minimum shNG version to use this plugin
    multi_instance: False
    classname: OneWire              # class containing the plugin

parameters:
    host:
        type: str
        mandatory: False
        description:
            de: 'owserver Hostnamen oder IP Adresse'
            en: 'owserver hostname or ip address'
            fr: "Nom de l'hôte ou adresse IP de l'owserver"

    port:
        type: int
        mandatory: False
        description:
            de: 'owserver Port'
            en: 'owserver port'
            fr: "Port de l'owserver"
    
item_attributes:
    name:
        type: str
        description:
            de: 'Name des Sensors'
            en: 'Sensor name'
            fr: 'Nom du capteur'
    
    type:
        type: str
        description:
            de: "Format der Sensordaten: 'num' oder 'bool'"
            en: "Sensor data format:  'num' or 'bool'"
            fr: "Format de données du capteur:  'num' ou 'bool'"

    ow_addr:
        type: str
        description:
            de: 'Sensoradresse im Format xx.yyyyyyyyyyyy'
            en: 'Sensor address in xx.yyyyyyyyyyyy format'
            fr: 'Adresse du capteur au format xx.yyyyyyyyyyyy'

    ow_sensor:
        type: str
        description:
            de: 'Sensortyp. Unterstützte Typen sind in der Plugin Readme zu finden'
            en: 'Sensor type. See plugin readme for supported types'
            fr: 'Type du capteur. Voir dans readme du plugin pour formats supportés'

