# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: gateway                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Anbindung einer oder mehrerer Philips HUE Bridges'
        en: ''
    maintainer: mworion
    tester: Sandman60
#    keywords: kwd1 kwd2            # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/blob/develop/mqtt/README.md        # url of documentation (wiki) page
    support: https://knx-user-forum.de/forum/supportforen/smarthome-py/41379-philips-hue-plugin-neu-v1-0-released

# Following entries are for Smart-Plugins:
#    version: 1.3.3                 # Plugin version
#    sh_minversion: 1.3             # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    multi_instance: False
    classname: HUE                  # class containing the plugin

#parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
    
#item_attributes:
    # Definition of item attributes defined by this plugin
    
